-- Fence Estimator Database Schema
-- Target platforms: PostgreSQL 14+ (primary) and MySQL 8+ (compatible with noted syntax adjustments)
-- File: /home/runner/work/fence-estimator/fence-estimator/database/schema.sql
-- This script creates core tables, constraints, views, triggers, sequences, and helper objects.

BEGIN;

-- =============================================================================
-- GENERAL NOTES
-- =============================================================================
-- 1. PostgreSQL is the reference dialect for executable objects in this file.
-- 2. MySQL 8+ can use the same table structure with these substitutions:
--    * BIGINT GENERATED BY DEFAULT AS IDENTITY -> BIGINT AUTO_INCREMENT
--    * TIMESTAMPTZ -> TIMESTAMP
--    * JSON -> JSON
--    * Trigger function syntax must be converted to MySQL BEFORE UPDATE triggers.
--    * PostgreSQL GIN full-text indexes should be replaced with MySQL FULLTEXT indexes.
-- 3. All money values use NUMERIC(12,2) to avoid floating point rounding issues.
-- 4. IDs are numeric to remain simple for exports and external integrations.

SET client_min_messages TO WARNING;

-- =============================================================================
-- COMMON FUNCTIONS
-- =============================================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION log_row_change()
RETURNS TRIGGER AS $$
DECLARE
    v_user_id BIGINT;
BEGIN
    BEGIN
        v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::BIGINT;
    EXCEPTION WHEN OTHERS THEN
        v_user_id := NULL;
    END;

    IF TG_OP = 'INSERT' THEN
        INSERT INTO audit_log (table_name, record_id, action, old_values, new_values, user_id, created_at)
        VALUES (TG_TABLE_NAME, NEW.id, TG_OP, NULL, to_json(NEW), v_user_id, CURRENT_TIMESTAMP);
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO audit_log (table_name, record_id, action, old_values, new_values, user_id, created_at)
        VALUES (TG_TABLE_NAME, NEW.id, TG_OP, to_json(OLD), to_json(NEW), v_user_id, CURRENT_TIMESTAMP);
        RETURN NEW;
    ELSE
        INSERT INTO audit_log (table_name, record_id, action, old_values, new_values, user_id, created_at)
        VALUES (TG_TABLE_NAME, OLD.id, TG_OP, to_json(OLD), NULL, v_user_id, CURRENT_TIMESTAMP);
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- SEQUENCES
-- =============================================================================
CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS customers_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS projects_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS estimates_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS estimate_items_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS gates_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS contracts_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS payments_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS photos_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
CREATE SEQUENCE IF NOT EXISTS audit_log_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;

-- -----------------------------------------------------------------------------
-- Table: users
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY DEFAULT nextval('users_id_seq'),
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'estimator' CHECK (role IN ('admin', 'estimator', 'crew', 'sales', 'viewer')),
    company VARCHAR(255),
    phone VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (position('@' in email) > 1)
);

COMMENT ON TABLE users IS 'Application users who can manage customers, projects, estimates, contracts, and photos.';
COMMENT ON COLUMN users.id IS 'Primary key for the user record.';
COMMENT ON COLUMN users.username IS 'Login-safe short name used in the estimator application.';
COMMENT ON COLUMN users.email IS 'Primary notification and login email address.';
COMMENT ON COLUMN users.password_hash IS 'Application password hash generated by the auth service.';
COMMENT ON COLUMN users.role IS 'Role-based permission key used by backend authorization middleware.';
COMMENT ON COLUMN users.company IS 'Optional company or department name for the user.';
COMMENT ON COLUMN users.phone IS 'Direct contact phone number for office or mobile use.';
COMMENT ON COLUMN users.created_at IS 'Timestamp when the user row was created.';
COMMENT ON COLUMN users.updated_at IS 'Timestamp automatically refreshed whenever the user row changes.';

-- -----------------------------------------------------------------------------
-- Table: customers
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT PRIMARY KEY DEFAULT nextval('customers_id_seq'),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(30),
    address VARCHAR(255),
    city VARCHAR(120),
    state VARCHAR(50),
    zip VARCHAR(20),
    company VARCHAR(255),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT,
    CONSTRAINT fk_customers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CHECK (email IS NULL OR position('@' in email) > 1)
);

COMMENT ON TABLE customers IS 'Fence customers and property owners tied to sales records.';
COMMENT ON COLUMN customers.id IS 'Primary key for the customer record.';
COMMENT ON COLUMN customers.first_name IS 'Customer first or given name.';
COMMENT ON COLUMN customers.last_name IS 'Customer last or family name.';
COMMENT ON COLUMN customers.email IS 'Primary customer email used for proposals and invoices.';
COMMENT ON COLUMN customers.phone IS 'Best phone number for scheduling site visits and follow-up.';
COMMENT ON COLUMN customers.address IS 'Billing or mailing street address.';
COMMENT ON COLUMN customers.city IS 'Billing or mailing city.';
COMMENT ON COLUMN customers.state IS 'Billing or mailing state or province.';
COMMENT ON COLUMN customers.zip IS 'Postal code.';
COMMENT ON COLUMN customers.company IS 'Customer company or HOA name when applicable.';
COMMENT ON COLUMN customers.notes IS 'Internal sales notes, preferences, lead source, or gate access details.';
COMMENT ON COLUMN customers.created_at IS 'Timestamp when the customer was entered into the CRM.';
COMMENT ON COLUMN customers.user_id IS 'Sales user who owns or created the customer record.';

-- -----------------------------------------------------------------------------
-- Table: projects
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT PRIMARY KEY DEFAULT nextval('projects_id_seq'),
    customer_id BIGINT NOT NULL,
    user_id BIGINT,
    name VARCHAR(255) NOT NULL,
    site_address VARCHAR(255),
    site_city VARCHAR(120),
    site_state VARCHAR(50),
    site_zip VARCHAR(20),
    project_type VARCHAR(30) NOT NULL DEFAULT 'residential' CHECK (project_type IN ('residential', 'commercial', 'industrial', 'agricultural', 'municipal', 'repair')),
    status VARCHAR(30) NOT NULL DEFAULT 'lead' CHECK (status IN ('lead', 'site-visit', 'estimating', 'proposal-sent', 'approved', 'scheduled', 'in-progress', 'completed', 'cancelled', 'archived')),
    notes TEXT,
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_projects_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

COMMENT ON TABLE projects IS 'Fence installation or repair jobs for a specific customer location.';
COMMENT ON COLUMN projects.id IS 'Primary key for the project record.';
COMMENT ON COLUMN projects.customer_id IS 'Foreign key to the customer requesting the job.';
COMMENT ON COLUMN projects.user_id IS 'Internal estimator or project manager assigned to the project.';
COMMENT ON COLUMN projects.name IS 'Human-readable job name shown in the project pipeline.';
COMMENT ON COLUMN projects.site_address IS 'Street address where the fence work will be performed.';
COMMENT ON COLUMN projects.site_city IS 'Project city.';
COMMENT ON COLUMN projects.site_state IS 'Project state.';
COMMENT ON COLUMN projects.site_zip IS 'Project postal code.';
COMMENT ON COLUMN projects.project_type IS 'High-level job classification for reporting.';
COMMENT ON COLUMN projects.status IS 'Pipeline status that drives dashboards and task lists.';
COMMENT ON COLUMN projects.notes IS 'Scope notes, survey requirements, HOA details, or scheduling constraints.';
COMMENT ON COLUMN projects.start_date IS 'Planned or actual project start date.';
COMMENT ON COLUMN projects.end_date IS 'Planned or actual project completion date.';
COMMENT ON COLUMN projects.created_at IS 'Timestamp when the project was first created.';
COMMENT ON COLUMN projects.updated_at IS 'Timestamp automatically refreshed whenever the project changes.';

-- -----------------------------------------------------------------------------
-- Table: estimates
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS estimates (
    id BIGINT PRIMARY KEY DEFAULT nextval('estimates_id_seq'),
    project_id BIGINT NOT NULL,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    status VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'internal-review', 'sent', 'approved', 'rejected', 'expired', 'converted')),
    fence_type VARCHAR(40) NOT NULL CHECK (fence_type IN ('chain-link', 'wood', 'vinyl', 'aluminum', 'ornamental-steel', 'composite', 'custom')),
    fence_height NUMERIC(6,2) NOT NULL CHECK (fence_height > 0),
    fence_color VARCHAR(60),
    linear_feet NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (linear_feet >= 0),
    post_count INTEGER NOT NULL DEFAULT 0 CHECK (post_count >= 0),
    materials_total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (materials_total >= 0),
    labor_total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (labor_total >= 0),
    extras_total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (extras_total >= 0),
    tax_rate NUMERIC(6,4) NOT NULL DEFAULT 0 CHECK (tax_rate >= 0),
    tax_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    grand_total NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (grand_total >= 0),
    markup_percent NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (markup_percent >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_estimates_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT uq_estimates_project_version UNIQUE (project_id, version)
);

COMMENT ON TABLE estimates IS 'Versioned project estimates with pricing, tax, markup, and total values.';
COMMENT ON COLUMN estimates.id IS 'Primary key for the estimate.';
COMMENT ON COLUMN estimates.project_id IS 'Project to which the estimate version belongs.';
COMMENT ON COLUMN estimates.version IS 'Version number starting at 1 for the first proposal.';
COMMENT ON COLUMN estimates.status IS 'Current lifecycle status for the estimate.';
COMMENT ON COLUMN estimates.fence_type IS 'Primary fence material/system type being estimated.';
COMMENT ON COLUMN estimates.fence_height IS 'Nominal fence height in feet or inches depending on application convention.';
COMMENT ON COLUMN estimates.fence_color IS 'Color/finish descriptor included on proposal output.';
COMMENT ON COLUMN estimates.linear_feet IS 'Total run length used to calculate material quantities.';
COMMENT ON COLUMN estimates.post_count IS 'Calculated or manually entered post count.';
COMMENT ON COLUMN estimates.materials_total IS 'Total extended material amount from estimate items and gates.';
COMMENT ON COLUMN estimates.labor_total IS 'Labor amount for install crews and shop fabrication.';
COMMENT ON COLUMN estimates.extras_total IS 'Permits, haul-off, mobilization, or special charges.';
COMMENT ON COLUMN estimates.tax_rate IS 'Sales tax rate stored as a decimal percentage such as 0.0825.';
COMMENT ON COLUMN estimates.tax_amount IS 'Calculated sales tax amount.';
COMMENT ON COLUMN estimates.subtotal IS 'Subtotal before sales tax.';
COMMENT ON COLUMN estimates.grand_total IS 'Total sell price including tax.';
COMMENT ON COLUMN estimates.markup_percent IS 'Applied markup percentage over cost basis.';
COMMENT ON COLUMN estimates.created_at IS 'Timestamp when the estimate version was created.';
COMMENT ON COLUMN estimates.updated_at IS 'Timestamp automatically refreshed whenever the estimate changes.';

-- -----------------------------------------------------------------------------
-- Table: estimate_items
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS estimate_items (
    id BIGINT PRIMARY KEY DEFAULT nextval('estimate_items_id_seq'),
    estimate_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL CHECK (category IN ('material', 'labor', 'equipment', 'freight', 'permit', 'subcontract', 'discount', 'other')),
    sku VARCHAR(100),
    description VARCHAR(255) NOT NULL,
    quantity NUMERIC(12,2) NOT NULL DEFAULT 1 CHECK (quantity >= 0),
    unit VARCHAR(30) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    notes TEXT,
    CONSTRAINT fk_estimate_items_estimate FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
);

COMMENT ON TABLE estimate_items IS 'Line-item level breakdown for materials, labor, and other estimate costs.';
COMMENT ON COLUMN estimate_items.id IS 'Primary key for the estimate line item.';
COMMENT ON COLUMN estimate_items.estimate_id IS 'Parent estimate record.';
COMMENT ON COLUMN estimate_items.category IS 'Cost bucket used for totals and reporting.';
COMMENT ON COLUMN estimate_items.sku IS 'Optional product catalog SKU used to source pricing.';
COMMENT ON COLUMN estimate_items.description IS 'Visible line item description for proposal output.';
COMMENT ON COLUMN estimate_items.quantity IS 'Extended quantity for the line item.';
COMMENT ON COLUMN estimate_items.unit IS 'Unit of measure such as each, foot, panel, roll, or hour.';
COMMENT ON COLUMN estimate_items.unit_price IS 'Price per unit before extension.';
COMMENT ON COLUMN estimate_items.total_price IS 'Extended line amount. Usually quantity multiplied by unit price.';
COMMENT ON COLUMN estimate_items.notes IS 'Installer notes, supplier reference, or assumptions.';

-- -----------------------------------------------------------------------------
-- Table: gates
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gates (
    id BIGINT PRIMARY KEY DEFAULT nextval('gates_id_seq'),
    estimate_id BIGINT NOT NULL,
    gate_type VARCHAR(30) NOT NULL CHECK (gate_type IN ('walk', 'double-drive', 'cantilever', 'rolling', 'ornamental', 'custom')),
    width NUMERIC(8,2) NOT NULL CHECK (width > 0),
    height NUMERIC(8,2) NOT NULL CHECK (height > 0),
    hardware_type VARCHAR(100),
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 1),
    unit_price NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
    total_price NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_price >= 0),
    CONSTRAINT fk_gates_estimate FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE
);

COMMENT ON TABLE gates IS 'Configured gate assemblies attached to estimates.';
COMMENT ON COLUMN gates.id IS 'Primary key for the gate row.';
COMMENT ON COLUMN gates.estimate_id IS 'Parent estimate record.';
COMMENT ON COLUMN gates.gate_type IS 'Configured gate style or drive arrangement.';
COMMENT ON COLUMN gates.width IS 'Gate width in feet.';
COMMENT ON COLUMN gates.height IS 'Gate height in feet.';
COMMENT ON COLUMN gates.hardware_type IS 'Latch, hinge, closer, or operator package description.';
COMMENT ON COLUMN gates.quantity IS 'Number of identical gates included.';
COMMENT ON COLUMN gates.unit_price IS 'Sell price per gate assembly.';
COMMENT ON COLUMN gates.total_price IS 'Extended sell price for the gate row.';

-- -----------------------------------------------------------------------------
-- Table: contracts
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contracts (
    id BIGINT PRIMARY KEY DEFAULT nextval('contracts_id_seq'),
    estimate_id BIGINT NOT NULL,
    status VARCHAR(25) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'signed', 'declined', 'cancelled', 'closed')),
    terms TEXT,
    signed_date DATE,
    signed_by VARCHAR(255),
    deposit_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (deposit_amount >= 0),
    deposit_paid BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_contracts_estimate FOREIGN KEY (estimate_id) REFERENCES estimates(id) ON DELETE CASCADE,
    CONSTRAINT uq_contracts_estimate UNIQUE (estimate_id)
);

COMMENT ON TABLE contracts IS 'Accepted commercial terms tied to a specific estimate version.';
COMMENT ON COLUMN contracts.id IS 'Primary key for the contract record.';
COMMENT ON COLUMN contracts.estimate_id IS 'Accepted estimate version tied to the contract.';
COMMENT ON COLUMN contracts.status IS 'Contract lifecycle state.';
COMMENT ON COLUMN contracts.terms IS 'Customer-facing terms, scope notes, and payment schedule text.';
COMMENT ON COLUMN contracts.signed_date IS 'Date when the contract was signed.';
COMMENT ON COLUMN contracts.signed_by IS 'Name of the signer recorded on the contract.';
COMMENT ON COLUMN contracts.deposit_amount IS 'Required deposit amount.';
COMMENT ON COLUMN contracts.deposit_paid IS 'Indicates whether the deposit has been collected.';
COMMENT ON COLUMN contracts.created_at IS 'Timestamp when the contract row was created.';

-- -----------------------------------------------------------------------------
-- Table: payments
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT PRIMARY KEY DEFAULT nextval('payments_id_seq'),
    contract_id BIGINT NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    payment_date DATE NOT NULL,
    payment_method VARCHAR(30) NOT NULL CHECK (payment_method IN ('cash', 'check', 'credit-card', 'ach', 'wire', 'financing', 'other')),
    reference_number VARCHAR(100),
    notes TEXT,
    CONSTRAINT fk_payments_contract FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
);

COMMENT ON TABLE payments IS 'Payments received against customer contracts.';
COMMENT ON COLUMN payments.id IS 'Primary key for the payment row.';
COMMENT ON COLUMN payments.contract_id IS 'Contract receiving the payment.';
COMMENT ON COLUMN payments.amount IS 'Payment amount applied to the contract.';
COMMENT ON COLUMN payments.payment_date IS 'Date funds were received.';
COMMENT ON COLUMN payments.payment_method IS 'Method used to collect payment.';
COMMENT ON COLUMN payments.reference_number IS 'Check number, ACH reference, or POS transaction ID.';
COMMENT ON COLUMN payments.notes IS 'Internal notes about the payment.';

-- -----------------------------------------------------------------------------
-- Table: products
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY DEFAULT nextval('products_id_seq'),
    sku VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(80) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    cost_price NUMERIC(12,2) NOT NULL CHECK (cost_price >= 0),
    stock_qty INTEGER NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE products IS 'Fence material and hardware catalog used to build estimate item lines.';
COMMENT ON COLUMN products.id IS 'Primary key for the product catalog row.';
COMMENT ON COLUMN products.sku IS 'Unique stock keeping unit code used for quoting and purchasing.';
COMMENT ON COLUMN products.name IS 'Customer-friendly product name.';
COMMENT ON COLUMN products.description IS 'Detailed internal product description.';
COMMENT ON COLUMN products.category IS 'Catalog grouping used for filtering and cost rollups.';
COMMENT ON COLUMN products.unit IS 'Primary stocking and quoting unit.';
COMMENT ON COLUMN products.unit_price IS 'Sell price used in estimates.';
COMMENT ON COLUMN products.cost_price IS 'Internal cost basis for margin calculations.';
COMMENT ON COLUMN products.stock_qty IS 'On-hand stocking quantity.';
COMMENT ON COLUMN products.active IS 'Whether the product can be quoted on new estimates.';

-- -----------------------------------------------------------------------------
-- Table: photos
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS photos (
    id BIGINT PRIMARY KEY DEFAULT nextval('photos_id_seq'),
    project_id BIGINT NOT NULL,
    filename VARCHAR(255) NOT NULL,
    label VARCHAR(255),
    upload_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT,
    CONSTRAINT fk_photos_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_photos_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

COMMENT ON TABLE photos IS 'Project site photos, sketches, and signed document imagery.';
COMMENT ON COLUMN photos.id IS 'Primary key for the photo record.';
COMMENT ON COLUMN photos.project_id IS 'Project associated with the uploaded image.';
COMMENT ON COLUMN photos.filename IS 'Stored file name or object key.';
COMMENT ON COLUMN photos.label IS 'Human-readable label shown in the UI.';
COMMENT ON COLUMN photos.upload_date IS 'Timestamp when the file was uploaded.';
COMMENT ON COLUMN photos.user_id IS 'User who uploaded the file.';

-- -----------------------------------------------------------------------------
-- Table: audit_log
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT PRIMARY KEY DEFAULT nextval('audit_log_id_seq'),
    table_name VARCHAR(100) NOT NULL,
    record_id BIGINT NOT NULL,
    action VARCHAR(20) NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    old_values JSON,
    new_values JSON,
    user_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

COMMENT ON TABLE audit_log IS 'Audit trail capturing row-level inserts, updates, and deletes for critical business tables.';
COMMENT ON COLUMN audit_log.id IS 'Primary key for the audit log row.';
COMMENT ON COLUMN audit_log.table_name IS 'Name of the table that changed.';
COMMENT ON COLUMN audit_log.record_id IS 'Primary key value of the changed row.';
COMMENT ON COLUMN audit_log.action IS 'Operation type that generated the audit record.';
COMMENT ON COLUMN audit_log.old_values IS 'Serialized JSON snapshot before the change.';
COMMENT ON COLUMN audit_log.new_values IS 'Serialized JSON snapshot after the change.';
COMMENT ON COLUMN audit_log.user_id IS 'Application user associated with the change when available.';
COMMENT ON COLUMN audit_log.created_at IS 'Timestamp when the audit row was written.';

-- =============================================================================
-- OWN SEQUENCES TO ID COLUMNS
-- =============================================================================
ALTER SEQUENCE users_id_seq OWNED BY users.id;
ALTER SEQUENCE customers_id_seq OWNED BY customers.id;
ALTER SEQUENCE projects_id_seq OWNED BY projects.id;
ALTER SEQUENCE estimates_id_seq OWNED BY estimates.id;
ALTER SEQUENCE estimate_items_id_seq OWNED BY estimate_items.id;
ALTER SEQUENCE gates_id_seq OWNED BY gates.id;
ALTER SEQUENCE contracts_id_seq OWNED BY contracts.id;
ALTER SEQUENCE payments_id_seq OWNED BY payments.id;
ALTER SEQUENCE products_id_seq OWNED BY products.id;
ALTER SEQUENCE photos_id_seq OWNED BY photos.id;
ALTER SEQUENCE audit_log_id_seq OWNED BY audit_log.id;

-- =============================================================================
-- PRIMARY BUSINESS INDEXES
-- =============================================================================
CREATE INDEX IF NOT EXISTS idx_customers_user_id ON customers (user_id);
CREATE INDEX IF NOT EXISTS idx_customers_name ON customers (last_name, first_name);
CREATE INDEX IF NOT EXISTS idx_customers_email ON customers (email);
CREATE INDEX IF NOT EXISTS idx_projects_customer_id ON projects (customer_id);
CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects (user_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects (status);
CREATE INDEX IF NOT EXISTS idx_projects_schedule ON projects (status, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_estimates_project_id ON estimates (project_id);
CREATE INDEX IF NOT EXISTS idx_estimates_status ON estimates (status);
CREATE INDEX IF NOT EXISTS idx_estimates_type_status ON estimates (fence_type, status);
CREATE INDEX IF NOT EXISTS idx_estimate_items_estimate_id ON estimate_items (estimate_id);
CREATE INDEX IF NOT EXISTS idx_estimate_items_category ON estimate_items (category);
CREATE INDEX IF NOT EXISTS idx_gates_estimate_id ON gates (estimate_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status ON contracts (status);
CREATE INDEX IF NOT EXISTS idx_payments_contract_id ON payments (contract_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON payments (payment_date);
CREATE INDEX IF NOT EXISTS idx_products_category_active ON products (category, active);
CREATE INDEX IF NOT EXISTS idx_products_name ON products (name);
CREATE INDEX IF NOT EXISTS idx_photos_project_id ON photos (project_id);
CREATE INDEX IF NOT EXISTS idx_photos_user_id ON photos (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_table_record ON audit_log (table_name, record_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created_at ON audit_log (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log (user_id);

-- PostgreSQL full-text search indexes. Replace with FULLTEXT indexes in MySQL 8+ as needed.
CREATE INDEX IF NOT EXISTS idx_customers_search ON customers USING GIN (to_tsvector('simple', coalesce(first_name, '') || ' ' || coalesce(last_name, '') || ' ' || coalesce(company, '') || ' ' || coalesce(email, '')));
CREATE INDEX IF NOT EXISTS idx_projects_search ON projects USING GIN (to_tsvector('simple', coalesce(name, '') || ' ' || coalesce(site_address, '') || ' ' || coalesce(site_city, '') || ' ' || coalesce(notes, '')));
CREATE INDEX IF NOT EXISTS idx_products_search ON products USING GIN (to_tsvector('simple', coalesce(sku, '') || ' ' || coalesce(name, '') || ' ' || coalesce(description, '') || ' ' || coalesce(category, '')));

-- =============================================================================
-- UPDATED_AT TRIGGERS
-- =============================================================================
DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;
CREATE TRIGGER trg_users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_projects_set_updated_at ON projects;
CREATE TRIGGER trg_projects_set_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_estimates_set_updated_at ON estimates;
CREATE TRIGGER trg_estimates_set_updated_at
BEFORE UPDATE ON estimates
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

-- =============================================================================
-- AUDIT TRIGGERS
-- =============================================================================
DROP TRIGGER IF EXISTS trg_customers_audit ON customers;
CREATE TRIGGER trg_customers_audit
AFTER INSERT OR UPDATE OR DELETE ON customers
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_projects_audit ON projects;
CREATE TRIGGER trg_projects_audit
AFTER INSERT OR UPDATE OR DELETE ON projects
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_estimates_audit ON estimates;
CREATE TRIGGER trg_estimates_audit
AFTER INSERT OR UPDATE OR DELETE ON estimates
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_estimate_items_audit ON estimate_items;
CREATE TRIGGER trg_estimate_items_audit
AFTER INSERT OR UPDATE OR DELETE ON estimate_items
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_gates_audit ON gates;
CREATE TRIGGER trg_gates_audit
AFTER INSERT OR UPDATE OR DELETE ON gates
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_contracts_audit ON contracts;
CREATE TRIGGER trg_contracts_audit
AFTER INSERT OR UPDATE OR DELETE ON contracts
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_payments_audit ON payments;
CREATE TRIGGER trg_payments_audit
AFTER INSERT OR UPDATE OR DELETE ON payments
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_products_audit ON products;
CREATE TRIGGER trg_products_audit
AFTER INSERT OR UPDATE OR DELETE ON products
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

DROP TRIGGER IF EXISTS trg_photos_audit ON photos;
CREATE TRIGGER trg_photos_audit
AFTER INSERT OR UPDATE OR DELETE ON photos
FOR EACH ROW
EXECUTE FUNCTION log_row_change();

-- =============================================================================
-- REPORTING VIEWS
-- =============================================================================
CREATE OR REPLACE VIEW v_customer_directory AS
SELECT
    c.id AS customer_id,
    c.first_name,
    c.last_name,
    c.company,
    c.email,
    c.phone,
    c.city,
    c.state,
    c.created_at,
    u.username AS owner_username,
    COUNT(p.id) AS project_count,
    MAX(p.updated_at) AS last_project_update
FROM customers c
LEFT JOIN users u ON u.id = c.user_id
LEFT JOIN projects p ON p.customer_id = c.id
GROUP BY c.id, c.first_name, c.last_name, c.company, c.email, c.phone, c.city, c.state, c.created_at, u.username;

CREATE OR REPLACE VIEW v_project_overview AS
SELECT
    p.id AS project_id,
    p.name AS project_name,
    p.project_type,
    p.status,
    p.site_address,
    p.site_city,
    p.site_state,
    p.site_zip,
    p.start_date,
    p.end_date,
    p.created_at,
    p.updated_at,
    c.id AS customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.company AS customer_company,
    c.phone AS customer_phone,
    u.username AS estimator_username,
    COUNT(e.id) AS estimate_count,
    MAX(e.version) AS latest_estimate_version,
    MAX(e.grand_total) FILTER (WHERE e.version = (SELECT MAX(e2.version) FROM estimates e2 WHERE e2.project_id = p.id)) AS latest_estimate_total
FROM projects p
JOIN customers c ON c.id = p.customer_id
LEFT JOIN users u ON u.id = p.user_id
LEFT JOIN estimates e ON e.project_id = p.id
GROUP BY p.id, c.id, u.username;

CREATE OR REPLACE VIEW v_estimate_pricing_summary AS
SELECT
    e.id AS estimate_id,
    e.project_id,
    p.name AS project_name,
    e.version,
    e.status,
    e.fence_type,
    e.fence_height,
    e.fence_color,
    e.linear_feet,
    e.post_count,
    e.materials_total,
    e.labor_total,
    e.extras_total,
    e.subtotal,
    e.tax_rate,
    e.tax_amount,
    e.grand_total,
    e.markup_percent,
    COALESCE(material_items.item_count, 0) AS material_item_count,
    COALESCE(gate_items.gate_count, 0) AS gate_count
FROM estimates e
JOIN projects p ON p.id = e.project_id
LEFT JOIN (
    SELECT estimate_id, COUNT(*) AS item_count
    FROM estimate_items
    WHERE category = 'material'
    GROUP BY estimate_id
) material_items ON material_items.estimate_id = e.id
LEFT JOIN (
    SELECT estimate_id, COUNT(*) AS gate_count
    FROM gates
    GROUP BY estimate_id
) gate_items ON gate_items.estimate_id = e.id;

CREATE OR REPLACE VIEW v_contract_payment_status AS
SELECT
    ct.id AS contract_id,
    ct.estimate_id,
    ct.status AS contract_status,
    ct.signed_date,
    ct.signed_by,
    ct.deposit_amount,
    ct.deposit_paid,
    e.project_id,
    p.name AS project_name,
    c.first_name || ' ' || c.last_name AS customer_name,
    e.grand_total AS contract_total,
    COALESCE(SUM(pm.amount), 0) AS amount_paid,
    GREATEST(e.grand_total - COALESCE(SUM(pm.amount), 0), 0) AS balance_due
FROM contracts ct
JOIN estimates e ON e.id = ct.estimate_id
JOIN projects p ON p.id = e.project_id
JOIN customers c ON c.id = p.customer_id
LEFT JOIN payments pm ON pm.contract_id = ct.id
GROUP BY ct.id, e.id, p.id, c.id;

CREATE OR REPLACE VIEW v_product_catalog AS
SELECT
    id,
    sku,
    name,
    category,
    unit,
    unit_price,
    cost_price,
    stock_qty,
    active,
    CASE
        WHEN unit_price = 0 THEN 0
        ELSE ROUND(((unit_price - cost_price) / unit_price) * 100, 2)
    END AS gross_margin_percent
FROM products;

CREATE OR REPLACE VIEW v_sales_pipeline AS
SELECT
    p.status,
    COUNT(*) AS project_count,
    COALESCE(SUM(e.grand_total), 0) AS total_pipeline_value,
    COALESCE(AVG(e.grand_total), 0) AS average_estimate_value
FROM projects p
LEFT JOIN estimates e ON e.project_id = p.id
AND e.version = (
    SELECT MAX(e2.version)
    FROM estimates e2
    WHERE e2.project_id = p.id
)
GROUP BY p.status
ORDER BY project_count DESC, p.status;

CREATE OR REPLACE VIEW v_photo_activity AS
SELECT
    ph.id AS photo_id,
    ph.project_id,
    p.name AS project_name,
    ph.filename,
    ph.label,
    ph.upload_date,
    u.username AS uploaded_by
FROM photos ph
JOIN projects p ON p.id = ph.project_id
LEFT JOIN users u ON u.id = ph.user_id;

CREATE OR REPLACE VIEW v_audit_feed AS
SELECT
    a.id,
    a.table_name,
    a.record_id,
    a.action,
    a.created_at,
    u.username AS actor_username,
    a.old_values,
    a.new_values
FROM audit_log a
LEFT JOIN users u ON u.id = a.user_id
ORDER BY a.created_at DESC, a.id DESC;

-- =============================================================================
-- OPTIONAL MYSQL NOTES
-- =============================================================================
-- MySQL equivalents for updated_at columns can be defined with:
--   updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- MySQL full-text equivalents can be created with statements such as:
--   ALTER TABLE customers ADD FULLTEXT INDEX ft_customers_name_company (first_name, last_name, company, email);
--   ALTER TABLE projects  ADD FULLTEXT INDEX ft_projects_name_address (name, site_address, site_city, notes);
--   ALTER TABLE products  ADD FULLTEXT INDEX ft_products_catalog (sku, name, description, category);

COMMIT;


-- =============================================================================
-- ADDITIONAL OPERATIONAL VIEWS
-- =============================================================================
CREATE OR REPLACE VIEW v_customer_lifetime_value AS
SELECT
    c.id AS customer_id,
    c.first_name,
    c.last_name,
    c.company,
    COUNT(DISTINCT p.id) AS project_count,
    COUNT(DISTINCT e.id) AS estimate_count,
    COALESCE(SUM(CASE WHEN e.status IN ('approved', 'converted') THEN e.grand_total ELSE 0 END), 0) AS approved_value,
    COALESCE(SUM(CASE WHEN ct.status IN ('signed', 'closed') THEN e.grand_total ELSE 0 END), 0) AS contracted_value,
    COALESCE(SUM(pm.amount), 0) AS payments_received
FROM customers c
LEFT JOIN projects p ON p.customer_id = c.id
LEFT JOIN estimates e ON e.project_id = p.id
LEFT JOIN contracts ct ON ct.estimate_id = e.id
LEFT JOIN payments pm ON pm.contract_id = ct.id
GROUP BY c.id;

CREATE OR REPLACE VIEW v_inventory_reorder AS
SELECT
    p.id,
    p.sku,
    p.name,
    p.category,
    p.stock_qty,
    p.unit,
    p.unit_price,
    p.cost_price,
    CASE
        WHEN p.category IN ('hardware', 'consumable', 'finish') THEN 50
        WHEN p.category LIKE 'chain-link%' THEN 20
        ELSE 10
    END AS reorder_point,
    CASE
        WHEN p.stock_qty <= 0 THEN 'out-of-stock'
        WHEN p.stock_qty <= 10 THEN 'critical'
        WHEN p.stock_qty <= 25 THEN 'watch'
        ELSE 'ok'
    END AS stock_status
FROM products p
WHERE p.active = TRUE;

CREATE OR REPLACE VIEW v_project_schedule_board AS
SELECT
    p.id AS project_id,
    p.name,
    p.status,
    p.start_date,
    p.end_date,
    p.site_city,
    p.site_state,
    c.first_name || ' ' || c.last_name AS customer_name,
    u.username AS assigned_user,
    COALESCE(e.grand_total, 0) AS latest_estimate_total
FROM projects p
JOIN customers c ON c.id = p.customer_id
LEFT JOIN users u ON u.id = p.user_id
LEFT JOIN estimates e ON e.project_id = p.id
AND e.version = (
    SELECT MAX(e2.version)
    FROM estimates e2
    WHERE e2.project_id = p.id
);

CREATE OR REPLACE VIEW v_estimate_margin_snapshot AS
SELECT
    e.id AS estimate_id,
    e.project_id,
    e.version,
    e.status,
    e.materials_total,
    e.labor_total,
    e.extras_total,
    e.subtotal,
    e.grand_total,
    e.markup_percent,
    ROUND(e.materials_total + e.labor_total + e.extras_total, 2) AS sell_before_tax,
    ROUND((e.materials_total + e.labor_total + e.extras_total) / NULLIF(1 + (e.markup_percent / 100.0), 0), 2) AS approximate_cost_basis,
    ROUND((e.materials_total + e.labor_total + e.extras_total) - ((e.materials_total + e.labor_total + e.extras_total) / NULLIF(1 + (e.markup_percent / 100.0), 0)), 2) AS implied_margin_value
FROM estimates e;

CREATE OR REPLACE VIEW v_contract_collections AS
SELECT
    ct.id AS contract_id,
    p.id AS project_id,
    p.name AS project_name,
    c.first_name || ' ' || c.last_name AS customer_name,
    ct.status,
    ct.deposit_amount,
    ct.deposit_paid,
    e.grand_total,
    COALESCE(SUM(pm.amount), 0) AS paid_to_date,
    GREATEST(e.grand_total - COALESCE(SUM(pm.amount), 0), 0) AS open_balance,
    MAX(pm.payment_date) AS last_payment_date
FROM contracts ct
JOIN estimates e ON e.id = ct.estimate_id
JOIN projects p ON p.id = e.project_id
JOIN customers c ON c.id = p.customer_id
LEFT JOIN payments pm ON pm.contract_id = ct.id
GROUP BY ct.id, p.id, c.id, e.id;

CREATE OR REPLACE VIEW v_user_workload AS
SELECT
    u.id AS user_id,
    u.username,
    u.role,
    COUNT(DISTINCT c.id) AS customers_owned,
    COUNT(DISTINCT p.id) AS projects_assigned,
    COUNT(DISTINCT e.id) AS estimates_owned,
    COALESCE(SUM(e.grand_total), 0) AS pipeline_value
FROM users u
LEFT JOIN customers c ON c.user_id = u.id
LEFT JOIN projects p ON p.user_id = u.id
LEFT JOIN estimates e ON e.project_id = p.id
GROUP BY u.id;

-- =============================================================================
-- REFERENCE QUERIES AND IMPLEMENTATION NOTES
-- =============================================================================
-- Example: fetch the newest estimate for a project.
-- SELECT *
-- FROM estimates
-- WHERE project_id = 42
-- ORDER BY version DESC
-- LIMIT 1;
--
-- Example: product search in PostgreSQL.
-- SELECT *
-- FROM products
-- WHERE to_tsvector('simple', coalesce(sku, '') || ' ' || coalesce(name, '') || ' ' || coalesce(description, ''))
--       @@ plainto_tsquery('simple', 'black chain link gate');
--
-- Example: customer collections dashboard.
-- SELECT *
-- FROM v_contract_collections
-- WHERE open_balance > 0
-- ORDER BY open_balance DESC;
--
-- MySQL implementation note:
--   Replace COMMENT ON statements with inline comments or a schema dictionary table.
--   Replace FILTER clauses in views with CASE expressions if using the same logical view definitions.
--   Replace JSON casts and trigger-function syntax with native MySQL JSON routines and BEFORE/AFTER triggers.
--
-- Recommended application conventions:
--   1. Set app.current_user_id before writes so audit rows capture the acting application user.
--   2. Recalculate estimates after line-item or gate changes using CALL calculate_estimate_total(...).
--   3. Prefer soft archival via project status instead of deleting historical production records.
--   4. Keep product SKUs immutable so historic estimate items remain traceable across price updates.
--   5. Use estimate versioning rather than overwriting sent or signed proposals.


-- =============================================================================
-- SCHEMA SUPPORT NOTES
-- =============================================================================
-- Recommended application startup order:
--   1. Apply schema.sql or run migration 001 and migration 002.
--   2. Apply procedures.sql.
--   3. Load seed.sql in non-production environments.
--   4. Run ANALYZE on PostgreSQL after the seed load completes.
--
-- Suggested backup/export sequence:
--   1. users
--   2. customers
--   3. projects
--   4. estimates
--   5. estimate_items
--   6. gates
--   7. contracts
--   8. payments
--   9. products
--   10. photos metadata
--   11. audit_log
--
-- Suggested restore/import sequence:
--   1. users
--   2. products
--   3. customers
--   4. projects
--   5. estimates
--   6. estimate_items
--   7. gates
--   8. contracts
--   9. payments
--   10. photos
--   11. audit_log
--
-- Future extension ideas that fit this schema cleanly:
--   * work_orders linked to contracts or projects
--   * supplier purchase_orders linked to products and jobs
--   * crews and timesheets linked to projects
--   * change_orders linked to estimate versions
--   * permit attachments linked through photos or a dedicated documents table
--   * cost history tables for dynamic product repricing
