BEGIN;
SET search_path TO public;
ALTER TABLE fence_specs ADD CONSTRAINT fence_specs_height_positive CHECK (height_feet > 0) NOT VALID;
ALTER TABLE fence_specs VALIDATE CONSTRAINT fence_specs_height_positive;
ALTER TABLE estimates ADD CONSTRAINT estimates_markup_pct_check CHECK (markup_pct >= 0) NOT VALID;
ALTER TABLE estimates VALIDATE CONSTRAINT estimates_markup_pct_check;
ALTER TABLE inventory ADD CONSTRAINT inventory_unit_cost_nonnegative CHECK (unit_cost >= 0) NOT VALID;
ALTER TABLE inventory VALIDATE CONSTRAINT inventory_unit_cost_nonnegative;
ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);
ALTER TABLE users ADD CONSTRAINT users_username_key UNIQUE (username);
ALTER TABLE inventory ADD CONSTRAINT inventory_sku_key UNIQUE (sku);
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$;
DROP TRIGGER IF EXISTS trg_projects_set_updated_at ON projects;
CREATE TRIGGER trg_projects_set_updated_at BEFORE UPDATE ON projects FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_fence_specs_set_updated_at ON fence_specs;
CREATE TRIGGER trg_fence_specs_set_updated_at BEFORE UPDATE ON fence_specs FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_estimates_set_updated_at ON estimates;
CREATE TRIGGER trg_estimates_set_updated_at BEFORE UPDATE ON estimates FOR EACH ROW EXECUTE FUNCTION set_updated_at();
DROP TRIGGER IF EXISTS trg_inventory_set_updated_at ON inventory;
CREATE TRIGGER trg_inventory_set_updated_at BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE FUNCTION set_updated_at();
INSERT INTO schema_migrations (version, description) VALUES ('003', 'Add Fence Depot constraints and update triggers') ON CONFLICT (version) DO NOTHING;
COMMIT;
